"""add profiles device tokens and invoice guard

Revision ID: 772358151d62
Revises: 0003
Create Date: 2026-07-29 15:43:49.977855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '772358151d62'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_device_tokens_hospital_id'), 'device_tokens', ['hospital_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_device_tokens_user', 'device_tokens', ['hospital_id', 'user_id', 'active'], unique=False, schema='auth')
    op.create_unique_constraint('uq_daily_sales_summary_hospital_date', 'daily_sales_summary', ['hospital_id', 'summary_date'], schema='analytics')
    op.create_unique_constraint('uq_invoices_hospital_sale', 'invoices', ['hospital_id', 'sale_id'], schema='billing')
    op.add_column('hospitals', sa.Column('signature_url', sa.Text(), nullable=True), schema='hospital')
    op.add_column('hospitals', sa.Column('gstin', sa.String(length=30), nullable=True), schema='hospital')
    op.execute("ALTER TABLE auth.device_tokens ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE auth.device_tokens FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON auth.device_tokens
        USING (
          current_setting('app.is_super_admin', true) = 'true'
          OR hospital_id::text = nullif(current_setting('app.hospital_id', true), '')
        )
        WITH CHECK (
          current_setting('app.is_super_admin', true) = 'true'
          OR hospital_id::text = nullif(current_setting('app.hospital_id', true), '')
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'gstin', schema='hospital')
    op.drop_column('hospitals', 'signature_url', schema='hospital')
    op.drop_constraint('uq_invoices_hospital_sale', 'invoices', schema='billing', type_='unique')
    op.drop_constraint('uq_daily_sales_summary_hospital_date', 'daily_sales_summary', schema='analytics', type_='unique')
    op.execute("DROP POLICY tenant_isolation ON auth.device_tokens")
    op.drop_index('ix_device_tokens_user', table_name='device_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_device_tokens_user_id'), table_name='device_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_device_tokens_hospital_id'), table_name='device_tokens', schema='auth')
    op.drop_table('device_tokens', schema='auth')
    # ### end Alembic commands ###
