"""create domain tables

Revision ID: f0d4bb0b681b
Revises: 0001
Create Date: 2026-07-29 15:37:16.774423
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f0d4bb0b681b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='auth'
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_table('hospitals',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='hospital'
    )
    op.create_index(op.f('ix_hospital_hospitals_status'), 'hospitals', ['status'], unique=False, schema='hospital')
    op.create_table('daily_sales_summary',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('sale_count', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('hospital_id', 'summary_date'),
    sa.UniqueConstraint('hospital_id', 'summary_date'),
    schema='analytics'
    )
    op.create_table('inventory_summary',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('total_skus', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('low_stock_count', sa.Integer(), nullable=False),
    sa.Column('out_of_stock_count', sa.Integer(), nullable=False),
    sa.Column('expiring_count', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('hospital_id'),
    schema='analytics'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_hospital_id'), 'users', ['hospital_id'], unique=False, schema='auth')
    op.create_index('ix_auth_users_hospital_role', 'users', ['hospital_id', 'role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_status'), 'users', ['status'], unique=False, schema='auth')
    op.create_table('branches',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'code'),
    schema='hospital'
    )
    op.create_index(op.f('ix_hospital_branches_hospital_id'), 'branches', ['hospital_id'], unique=False, schema='hospital')
    op.create_table('medicine_categories',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_medicine_categories_hospital_id'), 'medicine_categories', ['hospital_id'], unique=False, schema='inventory')
    op.create_table('documents',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('secure_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='patient'
    )
    op.create_index(op.f('ix_patient_documents_hospital_id'), 'documents', ['hospital_id'], unique=False, schema='patient')
    op.create_index('ix_patient_documents_owner', 'documents', ['hospital_id', 'owner_type', 'owner_id'], unique=False, schema='patient')
    op.create_table('suppliers',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name'),
    schema='supplier'
    )
    op.create_index(op.f('ix_supplier_suppliers_hospital_id'), 'suppliers', ['hospital_id'], unique=False, schema='supplier')
    op.create_table('audit_logs',
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_audit_logs_hospital_id'), 'audit_logs', ['hospital_id'], unique=False, schema='audit')
    op.create_index('ix_audit_entity', 'audit_logs', ['hospital_id', 'entity_type', 'entity_id'], unique=False, schema='audit')
    op.create_index('ix_audit_hospital_time', 'audit_logs', ['hospital_id', 'occurred_at'], unique=False, schema='audit')
    op.create_table('departments',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['hospital.branches.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name'),
    schema='hospital'
    )
    op.create_index(op.f('ix_hospital_departments_hospital_id'), 'departments', ['hospital_id'], unique=False, schema='hospital')
    op.create_table('medicines',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory.medicine_categories.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'barcode'),
    sa.UniqueConstraint('hospital_id', 'sku'),
    schema='inventory'
    )
    op.create_index('ix_inventory_medicine_name', 'medicines', ['hospital_id', 'name'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_medicines_hospital_id'), 'medicines', ['hospital_id'], unique=False, schema='inventory')
    op.create_table('notifications',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_index(op.f('ix_notification_notifications_hospital_id'), 'notifications', ['hospital_id'], unique=False, schema='notification')
    op.create_index(op.f('ix_notification_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='notification')
    op.create_index('ix_notification_user_time', 'notifications', ['user_id', 'created_at'], unique=False, schema='notification')
    op.create_table('patients',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('medical_record_number', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'medical_record_number'),
    schema='patient'
    )
    op.create_index('ix_patient_hospital_name', 'patients', ['hospital_id', 'name'], unique=False, schema='patient')
    op.create_index('ix_patient_hospital_phone', 'patients', ['hospital_id', 'phone'], unique=False, schema='patient')
    op.create_index(op.f('ix_patient_patients_hospital_id'), 'patients', ['hospital_id'], unique=False, schema='patient')
    op.create_table('purchase_orders',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_at', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'order_number'),
    schema='supplier'
    )
    op.create_index('ix_purchase_status', 'purchase_orders', ['hospital_id', 'status', 'created_at'], unique=False, schema='supplier')
    op.create_index(op.f('ix_supplier_purchase_orders_hospital_id'), 'purchase_orders', ['hospital_id'], unique=False, schema='supplier')
    op.create_table('doctors',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('registration_number', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['hospital.departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'registration_number'),
    sa.UniqueConstraint('user_id'),
    schema='doctor'
    )
    op.create_index(op.f('ix_doctor_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False, schema='doctor')
    op.create_index('ix_doctor_hospital_name', 'doctors', ['hospital_id', 'name'], unique=False, schema='doctor')
    op.create_table('rooms',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('room_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['hospital.branches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hospital.departments.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'number'),
    schema='hospital'
    )
    op.create_index(op.f('ix_hospital_rooms_hospital_id'), 'rooms', ['hospital_id'], unique=False, schema='hospital')
    op.create_table('medicine_batches',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['inventory.medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'medicine_id', 'batch_number'),
    schema='inventory'
    )
    op.create_index('ix_batch_expiry', 'medicine_batches', ['hospital_id', 'expiry_date'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_medicine_batches_hospital_id'), 'medicine_batches', ['hospital_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_medicine_batches_medicine_id'), 'medicine_batches', ['medicine_id'], unique=False, schema='inventory')
    op.create_table('notification_logs',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.notifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_index(op.f('ix_notification_notification_logs_notification_id'), 'notification_logs', ['notification_id'], unique=False, schema='notification')
    op.create_table('patient_clinical_records',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='patient'
    )
    op.create_index('ix_patient_clinical_type', 'patient_clinical_records', ['patient_id', 'record_type'], unique=False, schema='patient')
    op.create_index(op.f('ix_patient_patient_clinical_records_hospital_id'), 'patient_clinical_records', ['hospital_id'], unique=False, schema='patient')
    op.create_index(op.f('ix_patient_patient_clinical_records_patient_id'), 'patient_clinical_records', ['patient_id'], unique=False, schema='patient')
    op.create_table('patient_emergency_contacts',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('relationship', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='patient'
    )
    op.create_index(op.f('ix_patient_patient_emergency_contacts_hospital_id'), 'patient_emergency_contacts', ['hospital_id'], unique=False, schema='patient')
    op.create_index(op.f('ix_patient_patient_emergency_contacts_patient_id'), 'patient_emergency_contacts', ['patient_id'], unique=False, schema='patient')
    op.create_table('customers',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pharmacy'
    )
    op.create_index('ix_customer_hospital_phone', 'customers', ['hospital_id', 'phone'], unique=False, schema='pharmacy')
    op.create_index(op.f('ix_pharmacy_customers_hospital_id'), 'customers', ['hospital_id'], unique=False, schema='pharmacy')
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['inventory.medicines.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['supplier.purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='supplier'
    )
    op.create_index(op.f('ix_supplier_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False, schema='supplier')
    op.create_table('appointments',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['hospital.branches.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='appointment'
    )
    op.create_index(op.f('ix_appointment_appointments_hospital_id'), 'appointments', ['hospital_id'], unique=False, schema='appointment')
    op.create_index(op.f('ix_appointment_appointments_status'), 'appointments', ['status'], unique=False, schema='appointment')
    op.create_index('ix_appointment_doctor_time', 'appointments', ['hospital_id', 'doctor_id', 'starts_at'], unique=False, schema='appointment')
    op.create_index('ix_appointment_patient_time', 'appointments', ['hospital_id', 'patient_id', 'starts_at'], unique=False, schema='appointment')
    op.create_table('doctor_leaves',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='doctor'
    )
    op.create_index(op.f('ix_doctor_doctor_leaves_doctor_id'), 'doctor_leaves', ['doctor_id'], unique=False, schema='doctor')
    op.create_index(op.f('ix_doctor_doctor_leaves_hospital_id'), 'doctor_leaves', ['hospital_id'], unique=False, schema='doctor')
    op.create_table('doctor_schedules',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['hospital.branches.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'branch_id', 'weekday', 'start_time'),
    schema='doctor'
    )
    op.create_index(op.f('ix_doctor_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False, schema='doctor')
    op.create_index(op.f('ix_doctor_doctor_schedules_hospital_id'), 'doctor_schedules', ['hospital_id'], unique=False, schema='doctor')
    op.create_table('stock',
    sa.Column('medicine_batch_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('available_quantity >= 0'),
    sa.CheckConstraint('damaged_quantity >= 0'),
    sa.CheckConstraint('reserved_quantity >= 0'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_batch_id'], ['inventory.medicine_batches.id'], ),
    sa.PrimaryKeyConstraint('medicine_batch_id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_hospital_id'), 'stock', ['hospital_id'], unique=False, schema='inventory')
    op.create_table('stock_transactions',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('medicine_batch_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_delta <> 0'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_batch_id'], ['inventory.medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_transactions_hospital_id'), 'stock_transactions', ['hospital_id'], unique=False, schema='inventory')
    op.create_index('ix_stock_tx_batch_time', 'stock_transactions', ['medicine_batch_id', 'occurred_at'], unique=False, schema='inventory')
    op.create_index('ix_stock_tx_reference', 'stock_transactions', ['hospital_id', 'reference_type', 'reference_id'], unique=False, schema='inventory')
    op.create_table('medicine_sales',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('sale_number', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('upi_transaction_ref', sa.String(length=160), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['pharmacy.customers.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'sale_number'),
    schema='pharmacy'
    )
    op.create_index(op.f('ix_pharmacy_medicine_sales_hospital_id'), 'medicine_sales', ['hospital_id'], unique=False, schema='pharmacy')
    op.create_index('ix_sale_hospital_time', 'medicine_sales', ['hospital_id', 'created_at'], unique=False, schema='pharmacy')
    op.create_table('appointment_status_logs',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointments.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='appointment'
    )
    op.create_index(op.f('ix_appointment_appointment_status_logs_appointment_id'), 'appointment_status_logs', ['appointment_id'], unique=False, schema='appointment')
    op.create_index(op.f('ix_appointment_appointment_status_logs_hospital_id'), 'appointment_status_logs', ['hospital_id'], unique=False, schema='appointment')
    op.create_table('invoices',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy.medicine_sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'invoice_number'),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_invoices_hospital_id'), 'invoices', ['hospital_id'], unique=False, schema='billing')
    op.create_index('ix_invoice_patient_time', 'invoices', ['hospital_id', 'patient_id', 'created_at'], unique=False, schema='billing')
    op.create_table('consultations',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id'),
    schema='consultation'
    )
    op.create_index(op.f('ix_consultation_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False, schema='consultation')
    op.create_index(op.f('ix_consultation_consultations_hospital_id'), 'consultations', ['hospital_id'], unique=False, schema='consultation')
    op.create_index(op.f('ix_consultation_consultations_patient_id'), 'consultations', ['patient_id'], unique=False, schema='consultation')
    op.create_table('credit_ledger',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['pharmacy.customers.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy.medicine_sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='payment'
    )
    op.create_index('ix_credit_doctor_time', 'credit_ledger', ['hospital_id', 'doctor_id', 'created_at'], unique=False, schema='payment')
    op.create_index(op.f('ix_payment_credit_ledger_hospital_id'), 'credit_ledger', ['hospital_id'], unique=False, schema='payment')
    op.create_table('medicine_sale_items',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('medicine_batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_batch_id'], ['inventory.medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy.medicine_sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pharmacy'
    )
    op.create_index(op.f('ix_pharmacy_medicine_sale_items_sale_id'), 'medicine_sale_items', ['sale_id'], unique=False, schema='pharmacy')
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing.invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False, schema='billing')
    op.create_table('payments',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transaction_reference', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing.invoices.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy.medicine_sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'transaction_reference'),
    schema='payment'
    )
    op.create_index('ix_payment_invoice_time', 'payments', ['invoice_id', 'created_at'], unique=False, schema='payment')
    op.create_index(op.f('ix_payment_payments_hospital_id'), 'payments', ['hospital_id'], unique=False, schema='payment')
    op.create_table('prescriptions',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultation.consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prescription'
    )
    op.create_index(op.f('ix_prescription_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False, schema='prescription')
    op.create_index(op.f('ix_prescription_prescriptions_hospital_id'), 'prescriptions', ['hospital_id'], unique=False, schema='prescription')
    op.create_index(op.f('ix_prescription_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False, schema='prescription')
    op.create_table('refunds',
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.hospitals.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='payment'
    )
    op.create_index(op.f('ix_payment_refunds_hospital_id'), 'refunds', ['hospital_id'], unique=False, schema='payment')
    op.create_index(op.f('ix_payment_refunds_payment_id'), 'refunds', ['payment_id'], unique=False, schema='payment')
    op.create_table('prescription_items',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prescription'
    )
    op.create_index(op.f('ix_prescription_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False, schema='prescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_prescription_items_prescription_id'), table_name='prescription_items', schema='prescription')
    op.drop_table('prescription_items', schema='prescription')
    op.drop_index(op.f('ix_payment_refunds_payment_id'), table_name='refunds', schema='payment')
    op.drop_index(op.f('ix_payment_refunds_hospital_id'), table_name='refunds', schema='payment')
    op.drop_table('refunds', schema='payment')
    op.drop_index(op.f('ix_prescription_prescriptions_patient_id'), table_name='prescriptions', schema='prescription')
    op.drop_index(op.f('ix_prescription_prescriptions_hospital_id'), table_name='prescriptions', schema='prescription')
    op.drop_index(op.f('ix_prescription_prescriptions_doctor_id'), table_name='prescriptions', schema='prescription')
    op.drop_table('prescriptions', schema='prescription')
    op.drop_index(op.f('ix_payment_payments_hospital_id'), table_name='payments', schema='payment')
    op.drop_index('ix_payment_invoice_time', table_name='payments', schema='payment')
    op.drop_table('payments', schema='payment')
    op.drop_index(op.f('ix_billing_invoice_items_invoice_id'), table_name='invoice_items', schema='billing')
    op.drop_table('invoice_items', schema='billing')
    op.drop_index(op.f('ix_pharmacy_medicine_sale_items_sale_id'), table_name='medicine_sale_items', schema='pharmacy')
    op.drop_table('medicine_sale_items', schema='pharmacy')
    op.drop_index(op.f('ix_payment_credit_ledger_hospital_id'), table_name='credit_ledger', schema='payment')
    op.drop_index('ix_credit_doctor_time', table_name='credit_ledger', schema='payment')
    op.drop_table('credit_ledger', schema='payment')
    op.drop_index(op.f('ix_consultation_consultations_patient_id'), table_name='consultations', schema='consultation')
    op.drop_index(op.f('ix_consultation_consultations_hospital_id'), table_name='consultations', schema='consultation')
    op.drop_index(op.f('ix_consultation_consultations_doctor_id'), table_name='consultations', schema='consultation')
    op.drop_table('consultations', schema='consultation')
    op.drop_index('ix_invoice_patient_time', table_name='invoices', schema='billing')
    op.drop_index(op.f('ix_billing_invoices_hospital_id'), table_name='invoices', schema='billing')
    op.drop_table('invoices', schema='billing')
    op.drop_index(op.f('ix_appointment_appointment_status_logs_hospital_id'), table_name='appointment_status_logs', schema='appointment')
    op.drop_index(op.f('ix_appointment_appointment_status_logs_appointment_id'), table_name='appointment_status_logs', schema='appointment')
    op.drop_table('appointment_status_logs', schema='appointment')
    op.drop_index('ix_sale_hospital_time', table_name='medicine_sales', schema='pharmacy')
    op.drop_index(op.f('ix_pharmacy_medicine_sales_hospital_id'), table_name='medicine_sales', schema='pharmacy')
    op.drop_table('medicine_sales', schema='pharmacy')
    op.drop_index('ix_stock_tx_reference', table_name='stock_transactions', schema='inventory')
    op.drop_index('ix_stock_tx_batch_time', table_name='stock_transactions', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_transactions_hospital_id'), table_name='stock_transactions', schema='inventory')
    op.drop_table('stock_transactions', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_hospital_id'), table_name='stock', schema='inventory')
    op.drop_table('stock', schema='inventory')
    op.drop_index(op.f('ix_doctor_doctor_schedules_hospital_id'), table_name='doctor_schedules', schema='doctor')
    op.drop_index(op.f('ix_doctor_doctor_schedules_doctor_id'), table_name='doctor_schedules', schema='doctor')
    op.drop_table('doctor_schedules', schema='doctor')
    op.drop_index(op.f('ix_doctor_doctor_leaves_hospital_id'), table_name='doctor_leaves', schema='doctor')
    op.drop_index(op.f('ix_doctor_doctor_leaves_doctor_id'), table_name='doctor_leaves', schema='doctor')
    op.drop_table('doctor_leaves', schema='doctor')
    op.drop_index('ix_appointment_patient_time', table_name='appointments', schema='appointment')
    op.drop_index('ix_appointment_doctor_time', table_name='appointments', schema='appointment')
    op.drop_index(op.f('ix_appointment_appointments_status'), table_name='appointments', schema='appointment')
    op.drop_index(op.f('ix_appointment_appointments_hospital_id'), table_name='appointments', schema='appointment')
    op.drop_table('appointments', schema='appointment')
    op.drop_index(op.f('ix_supplier_purchase_order_items_purchase_order_id'), table_name='purchase_order_items', schema='supplier')
    op.drop_table('purchase_order_items', schema='supplier')
    op.drop_index(op.f('ix_pharmacy_customers_hospital_id'), table_name='customers', schema='pharmacy')
    op.drop_index('ix_customer_hospital_phone', table_name='customers', schema='pharmacy')
    op.drop_table('customers', schema='pharmacy')
    op.drop_index(op.f('ix_patient_patient_emergency_contacts_patient_id'), table_name='patient_emergency_contacts', schema='patient')
    op.drop_index(op.f('ix_patient_patient_emergency_contacts_hospital_id'), table_name='patient_emergency_contacts', schema='patient')
    op.drop_table('patient_emergency_contacts', schema='patient')
    op.drop_index(op.f('ix_patient_patient_clinical_records_patient_id'), table_name='patient_clinical_records', schema='patient')
    op.drop_index(op.f('ix_patient_patient_clinical_records_hospital_id'), table_name='patient_clinical_records', schema='patient')
    op.drop_index('ix_patient_clinical_type', table_name='patient_clinical_records', schema='patient')
    op.drop_table('patient_clinical_records', schema='patient')
    op.drop_index(op.f('ix_notification_notification_logs_notification_id'), table_name='notification_logs', schema='notification')
    op.drop_table('notification_logs', schema='notification')
    op.drop_index(op.f('ix_inventory_medicine_batches_medicine_id'), table_name='medicine_batches', schema='inventory')
    op.drop_index(op.f('ix_inventory_medicine_batches_hospital_id'), table_name='medicine_batches', schema='inventory')
    op.drop_index('ix_batch_expiry', table_name='medicine_batches', schema='inventory')
    op.drop_table('medicine_batches', schema='inventory')
    op.drop_index(op.f('ix_hospital_rooms_hospital_id'), table_name='rooms', schema='hospital')
    op.drop_table('rooms', schema='hospital')
    op.drop_index('ix_doctor_hospital_name', table_name='doctors', schema='doctor')
    op.drop_index(op.f('ix_doctor_doctors_hospital_id'), table_name='doctors', schema='doctor')
    op.drop_table('doctors', schema='doctor')
    op.drop_index(op.f('ix_supplier_purchase_orders_hospital_id'), table_name='purchase_orders', schema='supplier')
    op.drop_index('ix_purchase_status', table_name='purchase_orders', schema='supplier')
    op.drop_table('purchase_orders', schema='supplier')
    op.drop_index(op.f('ix_patient_patients_hospital_id'), table_name='patients', schema='patient')
    op.drop_index('ix_patient_hospital_phone', table_name='patients', schema='patient')
    op.drop_index('ix_patient_hospital_name', table_name='patients', schema='patient')
    op.drop_table('patients', schema='patient')
    op.drop_index('ix_notification_user_time', table_name='notifications', schema='notification')
    op.drop_index(op.f('ix_notification_notifications_user_id'), table_name='notifications', schema='notification')
    op.drop_index(op.f('ix_notification_notifications_hospital_id'), table_name='notifications', schema='notification')
    op.drop_table('notifications', schema='notification')
    op.drop_index(op.f('ix_inventory_medicines_hospital_id'), table_name='medicines', schema='inventory')
    op.drop_index('ix_inventory_medicine_name', table_name='medicines', schema='inventory')
    op.drop_table('medicines', schema='inventory')
    op.drop_index(op.f('ix_hospital_departments_hospital_id'), table_name='departments', schema='hospital')
    op.drop_table('departments', schema='hospital')
    op.drop_index('ix_audit_hospital_time', table_name='audit_logs', schema='audit')
    op.drop_index('ix_audit_entity', table_name='audit_logs', schema='audit')
    op.drop_index(op.f('ix_audit_audit_logs_hospital_id'), table_name='audit_logs', schema='audit')
    op.drop_table('audit_logs', schema='audit')
    op.drop_index(op.f('ix_supplier_suppliers_hospital_id'), table_name='suppliers', schema='supplier')
    op.drop_table('suppliers', schema='supplier')
    op.drop_index('ix_patient_documents_owner', table_name='documents', schema='patient')
    op.drop_index(op.f('ix_patient_documents_hospital_id'), table_name='documents', schema='patient')
    op.drop_table('documents', schema='patient')
    op.drop_index(op.f('ix_inventory_medicine_categories_hospital_id'), table_name='medicine_categories', schema='inventory')
    op.drop_table('medicine_categories', schema='inventory')
    op.drop_index(op.f('ix_hospital_branches_hospital_id'), table_name='branches', schema='hospital')
    op.drop_table('branches', schema='hospital')
    op.drop_index(op.f('ix_auth_users_status'), table_name='users', schema='auth')
    op.drop_index('ix_auth_users_hospital_role', table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_hospital_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('role_permissions', schema='auth')
    op.drop_table('inventory_summary', schema='analytics')
    op.drop_table('daily_sales_summary', schema='analytics')
    op.drop_index(op.f('ix_hospital_hospitals_status'), table_name='hospitals', schema='hospital')
    op.drop_table('hospitals', schema='hospital')
    op.drop_table('roles', schema='auth')
    op.drop_table('permissions', schema='auth')
    # ### end Alembic commands ###
